# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
os:
  - linux
  - osx
julia:
  - 0.6
notifications:
  email: false
addons:
      apt_packages:
        - gfortran
after_success:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.add("Ipopt")' # temp fix
  - julia -e 'Pkg.build("Ipopt")' # temp fix
  - julia -e 'Pkg.test("VehicleModels")'
